# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'typing_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTime, QTimer


import random
import time

easy_sentences = ["გრძელი სიტყვა მოკლედ ითქმის.",
                  "ეს არის მარტივი წინადადება.",
                  "სხვა სხვისა ომსა ბრძენია.",
                  "ბაყაყი წყალში ყიყინებს."]

medium_sentences = ["დღეს სკოლაში ძალიან საინტერესო გაკვეთილი გვქონდა.",
                    "სჯობს სახელისა მოხვეჭა ყოველსა მოსახვეჭელსა.",
                    "რასაცა გასცემ შენია, რაც არა, დაკარგულია!"]

hard_sentences = ["თეთრი თრითინა თეთრ თრთვილზე თრთოდა.",
                  "გახსოვდეს, რომ ქვეყანაზე ქაღალდის გარდა არის კიდევ სინდისი",
                  "გამაინდუსტრიონალიზაციონალისტები"]



class Ui_MainWindow(object):


    def display_random_sentence(self):
        if self.radioButton_1.isChecked():
            sentence = random.choice(easy_sentences)
        elif self.radioButton_2.isChecked():
            sentence = random.choice(medium_sentences)
        elif self.radioButton_3.isChecked():
            sentence = random.choice(hard_sentences)
        else:
            sentence = "გთხოვთ აირჩიოთ სირთულე."




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(190, 140, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.button_start.setFont(font)
        self.button_start.setIconSize(QtCore.QSize(20, 20))
        self.button_start.setObjectName("button_start")
        self.line_input = QtWidgets.QLineEdit(self.centralwidget)
        self.line_input.setGeometry(QtCore.QRect(50, 320, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.line_input.setFont(font)
        self.line_input.setText("")
        self.line_input.setObjectName("line_input")
        self.sentence = QtWidgets.QTextEdit(self.centralwidget)
        self.sentence.setGeometry(QtCore.QRect(50, 210, 631, 71))
        self.sentence.setObjectName("sentence")
        self.sentence.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(11)  # აქ შეცვალე ზომა
        font.setFamily("Sylfaen")  # ან სხვა ფონტი, მაგ. "Arial", "BPG Glaho", "Tahoma"
        self.sentence.setFont(font)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 280, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_timer = QtWidgets.QLabel(self.centralwidget)
        self.label_timer.setGeometry(QtCore.QRect(60, 390, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_timer.setFont(font)
        self.label_timer.setText("")
        self.label_timer.setObjectName("label_timer")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(320, 380, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.group_difficullty = QtWidgets.QGroupBox(self.centralwidget)
        self.group_difficullty.setGeometry(QtCore.QRect(30, 10, 181, 121))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.group_difficullty.setFont(font)
        self.group_difficullty.setObjectName("group_difficullty")
        self.radioButton_1 = QtWidgets.QRadioButton(self.group_difficullty)
        self.radioButton_1.setGeometry(QtCore.QRect(0, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.group_difficullty)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 60, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.group_difficullty)
        self.radioButton_3.setGeometry(QtCore.QRect(0, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_start.clicked.connect(self.display_random_sentence)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_start.setText(_translate("MainWindow", "თამაშის დაწყება"))
        self.label_2.setText(_translate("MainWindow", "შეიყვანეთ იდენტური ტექსტი:"))
        self.group_difficullty.setTitle(_translate("MainWindow", "სირთულე:"))
        self.radioButton_1.setText(_translate("MainWindow", "მარტივი"))
        self.radioButton_2.setText(_translate("MainWindow", "საშუალო"))
        self.radioButton_3.setText(_translate("MainWindow", "რთული"))

class TypingGame(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.timer = QTimer()
        self.timer.timeout.connect(self.update_timer)
        self.time_left = 10
        self.start_time = None

        self.ui.button_start.clicked.connect(self.start_game)
        self.ui.line_input.returnPressed.connect(self.check_input)

    def start_game(self):
        if not (self.ui.radioButton_1.isChecked() or
                self.ui.radioButton_2.isChecked() or
                self.ui.radioButton_3.isChecked()):
            self.ui.label_result.setText(" გთხოვ აირჩიე სირთულის დონე!")
            return
        self.time_left = 10
        self.ui.label_timer.setText(f"დრო: {self.time_left}")
        self.ui.label_result.setText("")
        self.ui.line_input.setText("")
        self.ui.line_input.setEnabled(True)
        self.ui.line_input.setFocus()

        if self.ui.radioButton_1.isChecked():
            sentence = random.choice(easy_sentences)
        elif self.ui.radioButton_2.isChecked():
            sentence = random.choice(medium_sentences)
        elif self.ui.radioButton_3.isChecked():
            sentence = random.choice(hard_sentences)
        else:
            sentence = "გთხოვთ აირჩიოთ სირთულე."

        self.ui.sentence.setPlainText(sentence)

        self.start_time = time.time()
        self.timer.start(1000)

    def update_timer(self):
        self.time_left -= 1
        self.ui.label_timer.setText(f"დრო: {self.time_left}")

        if self.time_left <= 0:
            self.timer.stop()
            self.ui.line_input.setEnabled(False)
            self.ui.label_result.setText(" დრო ამოიწურა! სცადე თავიდან.")

    def check_input(self):
        typed_text = self.ui.line_input.text()
        target_text = self.ui.sentence.toPlainText()

        if typed_text == target_text:
            self.timer.stop()
            elapsed = time.time() - self.start_time
            self.ui.label_result.setText(f" სწორად აკრიფე! დრო: {elapsed:.1f} წმ")
            self.ui.line_input.setEnabled(False)
        else:
            self.ui.label_result.setText("  ტექსტი არ ემთხვევა!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = TypingGame()
    window.show()
    sys.exit(app.exec_())

